export const ADD_STOPWATCH = "ADD_STOPWATCH";

export const REMOVE_STOPWATCH = "REMOVE_STOPWATCH";

export const UPDATE_STOPWATCH_VALUE = "UPDATE_STOPWATCH_VALUE";

export const PLAY_STOPWATCH = "PLAY_STOPWATCH";

export const SET_STOPWATCHES = "SET_STOPWATCHES";
